name: alignvec
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8=hd037594_8
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - icu=78.1=h38cb7af_0
  - libexpat=2.7.3=haf25636_0
  - libffi=3.5.2=he5f378a_0
  - libiconv=1.18=h23cfdf5_2
  - liblzma=5.8.1=h39f12f2_2
  - libsqlite=3.51.1=h1b79a29_1
  - libxml2=2.15.1=h8d039ee_1
  - libxml2-16=2.15.1=h5ef1a60_1
  - libxslt=1.1.43=hb2570ba_1
  - libzlib=1.3.1=h8359307_2
  - lxml=6.0.2=py310hca4a255_2
  - ncurses=6.5=h5e97a16_3
  - openssl=3.6.0=h5503f6c_0
  - pip=25.3=pyh8b19718_0
  - python=3.10.19=hcd7f573_2_cpython
  - python_abi=3.10=8_cp310
  - readline=8.3=h46df422_0
  - setuptools=80.9.0=pyhff2d567_0
  - tk=8.6.13=h892fb3f_3
  - wheel=0.45.1=pyhd8ed1ab_1
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - anyio==4.12.0
      - appnope==0.1.4
      - asttokens==3.0.1
      - async-timeout==5.0.1
      - attrs==25.4.0
      - backcall==0.2.0
      - beautifulsoup4==4.14.3
      - bleach==6.3.0
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - click==8.3.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - datasets==4.4.2
      - decorator==5.2.1
      - defusedxml==0.7.1
      - dill==0.4.0
      - docopt==0.6.2
      - exceptiongroup==1.3.1
      - executing==2.2.1
      - fastjsonschema==2.21.2
      - filelock==3.20.1
      - fonttools==4.61.1
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.2.3
      - idna==3.11
      - ipython==8.12.3
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.5.3
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter-client==8.7.0
      - jupyter-core==5.9.1
      - jupyterlab-pygments==0.3.0
      - kiwisolver==1.4.9
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - matplotlib-inline==0.2.1
      - mistune==3.2.0
      - mpmath==1.3.0
      - multidict==6.7.0
      - multiprocess==0.70.18
      - nbclient==0.10.4
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - networkx==3.4.2
      - numpy==2.2.6
      - packaging==25.0
      - pandas==2.3.3
      - pandocfilters==1.5.1
      - parso==0.8.5
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pillow==12.0.0
      - pipreqs==0.5.0
      - platformdirs==4.5.1
      - pot==0.9.6.post1
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==22.0.0
      - pygments==2.19.2
      - pyparsing==3.3.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - referencing==0.37.0
      - requests==2.32.5
      - rpds-py==0.30.0
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - shellingham==1.5.4
      - six==1.17.0
      - soupsieve==2.8.1
      - stack-data==0.6.3
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - tinycss2==1.4.0
      - torch==2.9.1
      - torchvision==0.24.1
      - tornado==6.5.4
      - tqdm==4.67.1
      - traitlets==5.14.3
      - typer-slim==0.21.0
      - typing-extensions==4.15.0
      - tzdata==2025.3
      - urllib3==2.6.2
      - wcwidth==0.2.14
      - webencodings==0.5.1
      - xxhash==3.6.0
      - yarg==0.1.9
      - yarl==1.22.0
prefix: /opt/anaconda3/envs/alignvec
